import {motion} from 'framer-motion'
import {ArrowRight,Check,LockKeyhole} from 'lucide-react'
import {useNavigate,useSearchParams} from 'react-router-dom'
import {API_URL,api} from '../api'
import Logo from '../components/Logo'
import MailScene from '../components/MailScene'
const errors={google_not_configured:'Google OAuth is not configured yet.',microsoft_not_configured:'Microsoft OAuth is not configured yet.',invalid_oauth_state:'The sign-in request expired. Please try again.',oauth_failed:'The provider could not complete sign-in.'}
export default function Login(){const navigate=useNavigate();const[params]=useSearchParams();const error=params.get('error');async function demo(){await api('/api/auth/demo',{method:'POST'});navigate('/dashboard')}
return <main className="login-shell"><section className="login-visual"><div className="noise"/><Logo/><div className="scene"><MailScene/></div><motion.div className="visual-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><span className="pill">INTELLIGENT INBOX OPERATIONS</span><h1>Every message.<br/><em>Already understood.</em></h1><p>Turn email noise into a clear, prioritized workspace your team can act on.</p></motion.div><div className="trust-row"><span><Check/>Read-only access</span><span><Check/>Encrypted tokens</span><span><Check/>Disconnect anytime</span></div></section><section className="login-panel"><motion.div className="login-card" initial={{opacity:0,x:24}} animate={{opacity:1,x:0}}><div className="mobile-logo"><Logo dark/></div><p className="kicker">WELCOME TO INBOXPILOT</p><h2>Connect your workspace</h2><p className="muted">Choose the mailbox your team uses. We only request read access.</p>{error&&<div className="auth-error">{errors[error]||'Sign-in failed. Please try again.'}</div>}<a className="provider-button" href={`${API_URL}/api/auth/google`}><span className="provider-icon google">G</span><b>Continue with Google</b><ArrowRight size={18}/></a><a className="provider-button" href={`${API_URL}/api/auth/microsoft`}><span className="provider-icon microsoft"><i/><i/><i/><i/></span><b>Continue with Microsoft</b><ArrowRight size={18}/></a><div className="divider"><span>or explore safely</span></div><button className="demo-button" onClick={demo}>Open interactive demo</button><div className="security-note"><LockKeyhole size={17}/><span><b>Your inbox stays yours.</b> Credentials are encrypted and email content is never sold.</span></div><p className="legal">By continuing, you agree to our <a href="#">Terms</a> and <a href="#">Privacy Policy</a>.</p></motion.div></section></main>}
